version: '3'

services:

  portainer:
    container_name: portainer
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/docker/data/portainer:/data
  aria2:
    container_name: aria2
    build:
      context: ./
      dockerfile: Dockerfile-aria2
    restart: always
    ports:
      - "6800:6800"
      - "6881-6999:6881-6999"
    volumes:
      - /mnt/docker/conf/aria2:/config
      - /mnt/docker/data/downloads:/data
      - /mnt/docker/data/other/downloads:/downloads

  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser
    restart: always
    ports:
      - "8081:80"
    volumes:
      - /mnt/docker/conf/filebrowser/filebrowser.json:/.filebrowser.json
      - /mnt/docker/conf/filebrowser/database.db:/database.db
      - /mnt/docker/data:/srv

  caddy:
    container_name: caddy
    build:
      context: ./
      dockerfile: Dockerfile-caddy
    restart: always
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - /mnt/docker/conf/caddy:/config
      - /mnt/docker/data:/webroot

  gitea:
    container_name: gitea
    image: gitea/gitea
    restart: always
    ports:
      - "3000:3000"
      - "8822:22"
    volumes:
      - /mnt/docker/data/gitea:/data

  syncthing:
    container_name: syncthing
    image: syncthing/syncthing
    restart: always
    ports:
      - "22000:22000"
      - "8384:8384"
      - "21027:21027/udp"
    volumes:
      - /mnt/docker/conf/syncthing:/config
      - /mnt/docker/data/sync:/sync
      - /mnt/docker/data/sync:/data1
      - /mnt/docker/data/other/sync:/data2

  baidu-pcs:
    container_name: baidu-pcs
    build:
      context: ./
      dockerfile: Dockerfile-baiduPCS-Web
    restart: always
    ports:
      - "5299:5299"
    volumes:
      - /mnt/docker/data/BDdownloads:/root/Download
      - /mnt/docker/data/other/BDdownloads:/root/Downloads

  v2ray:
    container_name: v2ray
    image: v2ray/official
    restart: always
    ports:
      - "1081-1089:1081-1089"
      - "1091-1099:1091-1099/udp"
    volumes:
      - /mnt/docker/conf/v2ray/config.json:/etc/v2ray/config.json
