FROM alpine:edge

LABEL AUTHOR=AnRightHand

ENV ARCH=amd64
ENV BAIDUPCS_WEB_VERSION=3.6.8
ENV BAIDUPCS_WEB_URL=https://github.com/liuzhuoling2011/baidupcs-web/releases/download/${BAIDUPCS_WEB_VERSION}/BaiduPCS-Go-${BAIDUPCS_WEB_VERSION}-linux-${ARCH}.zip

WORKDIR /app

RUN apk add --no-cache wget bash gnupg unzip && \
 wget $BAIDUPCS_WEB_URL && \
 unzip BaiduPCS-Go-${BAIDUPCS_WEB_VERSION}-linux-${ARCH}.zip && \
 rm BaiduPCS-Go-${BAIDUPCS_WEB_VERSION}-linux-${ARCH}.zip && \
 cd BaiduPCS-Go-${BAIDUPCS_WEB_VERSION}-linux-${ARCH} && \
 mv BaiduPCS-Go .. && cd .. && \
 mv BaiduPCS-Go baidupcs && \
 chmod +x baidupcs

EXPOSE 5299

CMD "/app/baidupcs"

