version: '3'

services:

  portainer:
    container_name: portainer
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    network_mode: "bridge"
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/docker/data/portainer:/data
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "3"
      
  aria2:
    container_name: aria2
    build:
      context: ./
      dockerfile: Dockerfile-aria2
    restart: always
    network_mode: "host"
    ports:
      - "6800:6800"
      - "6881-6899:6881-6899/udp"
    volumes:
      - /mnt/docker/conf/aria2:/config
      - /mnt/docker/data/downloads:/data
      - /mnt/docker/data/other/downloads:/downloads
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "3"

  filebrowser:
    container_name: filebrowser
    build:
      context: ./
      dockerfile: Dockerfile-filebrowser
    restart: always
    network_mode: "bridge"
    ports:
      - "8081:80"
    volumes:
      - /mnt/docker/conf/filebrowser:/config
      - /mnt/docker/data:/srv
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "3"

  caddy:
    container_name: caddy
    build:
      context: ./
      dockerfile: Dockerfile-caddy
    restart: always
    network_mode: "bridge"
    ports:
      - "8080:80"
      - "8443:8443"
    volumes:
      - /mnt/docker/conf/caddy:/config
      - /mnt/docker/data:/webroot
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "3"

  gitea:
    container_name: gitea
    image: gitea/gitea
    restart: always
    network_mode: "bridge"
    ports:
      - "3000:3000"
      - "8822:22"
    volumes:
      - /mnt/docker/conf/gitea:/data
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "3"

  syncthing:
    container_name: syncthing
    build:
      context: ./
      dockerfile: Dockerfile-syncthing
    restart: always
    network_mode: "bridge"
    ports:
      - "22000:22000"
      - "8384:8384"
      - "21027:21027/udp"
    volumes:
      - /mnt/docker/conf/syncthing:/config
      - /mnt/docker/data/sync:/sync
      - /mnt/docker/data/sync:/data1
      - /mnt/docker/data/other/sync:/data2
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "3"

  baidu-pcs:
    container_name: baidu-pcs
    build:
      context: ./
      dockerfile: Dockerfile-baiduPCS-Web
    restart: always
    network_mode: "bridge"
    ports:
      - "5299:5299"
    volumes:
      - /mnt/docker/data/BDdownloads:/root/Download
      - /mnt/docker/data/other/BDdownloads:/root/Downloads
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "3"

  nexus3:
    container_name: nexus3
    image: sonatype/nexus3
    restart: always
    network_mode: "bridge"
    ports:
      - "8082:8081"
    volumes:
      - /mnt/docker/data/nexus3:/nexus-data
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "3"
      
  auto-qiandao:
    container_name: auto-qiandao
    build:
      context: ./
      dockerfile: Dockerfile-auto-qiandao
    restart: always
    network_mode: "bridge"
    ports:
      - "8083:80"
    volumes:
      - /mnt/docker/conf/qiandao:/config
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "3"
  
  v2ray:
    container_name: v2ray
    build:
      context: ./
      dockerfile: Dockerfile-v2
    restart: always
    network_mode: "host"
    ports:
      - "1081-1089:1081-1089"
      - "1091-1095:1091-1095/udp"
    volumes:
      - /mnt/docker/conf/v2ray/:/config
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "3"
