# 基础镜像
FROM python:2.7-alpine
# 维护者信息
LABEL maintainer "AnRightHand"

ENV QIANDAO_URL=https://github.com/binux/qiandao/archive/master.zip

ENV PORT 80
EXPOSE $PORT/tcp
# 添加挂载点
#VLUME ["/usr/src/app/"]
WORKDIR /app

# 基础镜像已经包含pip组件
RUN apk update && \
    apk add bash curl autoconf g++ unzip  && \
    curl -o master.zip -sSL $QIANDAO_URL && \
    unzip master.zip && \
    mv ./qiandao-master/* ./  && \
    pip install --no-cache-dir -r requirements.txt

CMD ["python","/app/run.py"]
