FROM alpine:edge

LABEL AUTHOR=AnRightHand

# install minidlna
RUN apk --no-cache add minidlna curl

EXPOSE 1900/udp
EXPOSE 8200

VOLUME /config

# Add config file
#ADD minidlna.conf /config/minidlna.conf
RUN mkdir /app && curl -sSL -o /app/minidlna.conf https://raw.githubusercontent.com/AnRightHand/rpi-dockers/master/minidlna/minidlna.conf && \
  mv -n /app/minidlna.conf /config/minidlna.conf

#ENTRYPOINT [ "/usr/sbin/minidlnad", "-S" ]
CMD /usr/sbin/minidlnad -f /config/minidlna.conf -S